apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: pf-tracker
spec:
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok:latest
          args: ["http", "app:3000", "--log", "stdout"]
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: authtoken
